version: '3.5'

services:
  backend:
    build: ./backend
    image: webrecorder/browsertrix-api
    ports:
      - 8000:8000

    env_file:
      - ./config.env

  mongo:
    image: mongo
    env_file:
      - ./config.env

    volumes:
      - mongodata:/data/db

  minio:
    image: minio/minio
    command: server /data
    ports:
      - 8010:9000

    volumes:
      - miniodata:/data

volumes:
  mongodata:
  miniodata:

