version: '3.5'

services:
  backend:
    build: ./backend
    image: webrecorder/browsertrix-api
    ports:
      - 8000:8000

    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    env_file:
      - ./config.env

    depends_on:
      - minio
      - mongo
      - scheduler

  scheduler:
    build: ./backend
    image: webrecorder/browsertrix-api
    command: python -u scheduler.py

    env_file:
      - ./config.env

    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

    env_file:
      - ./config.env

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001

    volumes:
      - miniodata:/data

    env_file:
      - ./config.env

  init_minio_bucket:
    image: minio/mc
    entrypoint: "/bin/sh"
    command: ['-c', 'mc mb local/test-bucket; mc policy set public local/test-bucket' ]

    env_file:
      - ./config.env

    depends_on:
      - minio



volumes:
  mongodata:
  miniodata:

