---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-env-config
  namespace: {{ .Release.Namespace }}

data:
  MONGO_HOST: localhost

  CRAWLER_NAMESPACE: {{ .Values.crawler_namespace }}
  CRAWLER_IMAGE: {{ .Values.crawler_image }}

  IN_CLUSTER: "1"
  K8S: "1"


---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongo_auth.username | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongo_auth.password | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: storage-auth
  namespace: {{ .Release.Namespace }}

type: Opaque
stringData:
  PASSWORD_SECRET: "{{ .Values.api_password_secret }}"

  MINIO_ROOT_USER: "{{ .Values.storage.access_key }}"
  MINIO_ROOT_PASSWORD: "{{ .Values.storage.secret_key }}"
 
  AWS_ACCESS_KEY_ID: "{{ .Values.storage.access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.storage.secret_key }}"
  AWS_ENDPOINT: "{{ .Values.storage.endpoint }}"
  #S3_FORCE_PATH_STYLE: "{{ .Values.storage.force_path_style | quote }}"

