name: Update assigned issues in Webrecorder Projects

on:
  issues:
    types: [assigned]

jobs:
  update-project-column:
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.GHPROJECT_TOKEN }}
          organization: webrecorder
          project_number: 9
          content_id: ${{ github.event.issue.id }}
          field: Status
          value: Todo
